<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4VG4ENC" name="Home" tests="2" failures="1" timestamp="9 Jan 2023 05:01:53 GMT" time="48.925" errors="0">
  <testcase name="launchHomePage_Test" time="5.403" classname="com.automation.ui.digitaldeployer.testcases.index.HomePageTest"/>
  <testcase name="continue_Test" time="15.417" classname="com.automation.ui.digitaldeployer.testcases.index.HomePageTest">
    <failure type="java.lang.AssertionError" message="ERROR WHILE EXECUTION ">
        <![CDATA[java.lang.AssertionError: ERROR WHILE EXECUTION
	at com.automation.ui.digitaldeployer.pageobjectsfactory.pageobject.index.pages.IndexPage.continueButton(HomePage.java:124)
	at com.automation.ui.digitaldeployer.testcases.index.HomePageTest.continue_Test(HomePageTest.java:60)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- continue_Test -->
</testsuite> <!-- Home -->
