<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4VG4ENC" name="Home" tests="3" failures="1" timestamp="11 Jan 2023 05:01:56 GMT" time="75.464" errors="0">
  <testcase name="launchHomePage_Test" time="1.529" classname="com.automation.ui.digitaldeployer.testcases.index.IndexPageTest"/>
  <testcase name="launchAddNewWorkspace_Test" time="38.822" classname="com.automation.ui.digitaldeployer.testcases.home.HomePageTest"/>
  <testcase name="launchAddNewWorkspacename_Test" time="21.775" classname="com.automation.ui.digitaldeployer.testcases.home.HomePageTest">
    <failure type="java.lang.AssertionError" message="ERROR WHILE EXECUTION ">
      <![CDATA[java.lang.AssertionError: ERROR WHILE EXECUTION 
	at com.automation.ui.digitaldeployer.pageobjectsfactory.pageobject.home.pages.HomePage.addwsname(HomePage.java:116)
	at com.automation.ui.digitaldeployer.testcases.home.HomePageTest.launchAddNewWorkspacename_Test(HomePageTest.java:107)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- launchAddNewWorkspacename_Test -->
</testsuite> <!-- Home -->
